### ISSUE TITLE
禁止访问文件目录

### ISSUE THREAD

**Issue by lizhongkan** [LinkinStars/sgfs#1]
现在可以访问文件目录，会列出目录下所有的文件。建议可在配置文件，关闭该功能，也就是禁止访问文件目录。这是为了针对外网时，避免展示所有文件给用户。用户只需要拿到对应的url，获取需要的文件即可。
看了下代码：sgfs.go有这么一段
// Generate a file directory index. If true, access to the root path can see all the files stored.
// In a production environment, it is recommended to set false
GenerateIndexPages: true,
是不是改成false就可以了？还不会用go，建议升级下。谢谢

**Comment by LinkinStars** [comment]
失误，我之前考虑到了，配置文件conf.yml中的generate_index_pages就是这个用的，这不过代码里面没读配置文件的信息，晚上修复，明天发布。万分感谢。

**Comment by LinkinStars** [comment]
好了最新的1.0.1版本已经修复，注意更新的时候不要手一抖把upload删掉了，里面是存你上传的文件，如果已经修改过conf.yml的话也备份一下，解压之后会被覆盖的。最新版只需要修改配置文件conf.yml中的generate_index_pages为false就可以禁止访问文件目录了。

**Comment by lizhongkan** [comment]
谢谢。测试可以了。
