### ISSUE TITLE
There was an error connecting to http://127.0.0.1:9001/upload-file.

### ISSUE THREAD

**Issue by OOMROO** [LinkinStars/sgfs#5]

**Comment by LinkinStars** [comment]
Can you describe exactly what happened when the error occurred?

**Comment by OOMROO** [comment]
运行startup.sh  postman提交文件就报这个错了

**Comment by LinkinStars** [comment]
能把具体的请求截个图吗？然后把返回的情况也截个图，你也可以查看当前目录下的log文件是否正常生成，是否在日志中有错误。

**Comment by OOMROO** [comment]
<img width="901" alt="WX20191108-164222@2x" src="https://user-images.githubusercontent.com/19899798/68462220-0f3fe280-0247-11ea-897b-8d430ce12817.png">

**Comment by OOMROO** [comment]
<img width="930" alt="WX20191108-164555@2x" src="https://user-images.githubusercontent.com/19899798/68462347-529a5100-0247-11ea-94bb-e91200d5616c.png">

**Comment by LinkinStars** [comment]
这个是release是linux版本的，只能在linux服务器上运行，所以你本地没有任何提示，我release下一个版本发个darwin给mac用好了。

新版本1.0.2已经发了，你可以下载darwin版本的试试看

**Comment by OOMROO** [comment]
![image](https://user-images.githubusercontent.com/19899798/68475917-5dafaa00-0264-11ea-8a35-e5b29b67ed71.png)
用的1.0.2 有log 日志了 报405 错误

**Comment by LinkinStars** [comment]
是啊，你用GET请求当然405了。。。应该用POST，然后把你要传的参数放body的form里面

**Comment by OOMROO** [comment]
是的 我忘了切换过来 用post 是ok 的 谢谢

**Comment by OOMROO** [comment]
非常🙏
